### ISSUE TITLE
Mechanics that need to be done

### ISSUE THREAD

**Issue by mbitzos** [mbitzos/Project-Vault#58]
This is a list, of mechanics that need to be done but haven't been given enough thought to be made into an issue:

~~parrying~~
~~using consumables~~
~~Attacking/Hit Framework update~~
~~Lock on design~~

**Comment by mbitzos** [comment]
updated attack/hit framework in cac82a71cbfb60973d7b559cc3ebc37f5989a1dc and f5d16c3aae463b93fdb0026a95ce2fe9dbaea8c0

**Comment by BenPetkovsek** [comment]
Using consumables finished in 275c84a0a3db72874a9d1fdd63bc0d21d4a2f897

**Comment by mbitzos** [comment]
parrying -> critical dodge finished in 0b58e3fe2a6ee1c1138e7e8a214224ec56520bc8
